default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: your_username
  password: your_password

development:
  <<: *default
  database: landetech_api_development

test:
  <<: *default
  database: landetech_api_test

production:
  <<: *default
  database: landetech_api_production
  username: landetech_api
  password: <%= ENV['LANDETECH_API_DATABASE_PASSWORD'] %>
